backend/djsf/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .serializers import router as serializersRouter

urlpatterns = [
    url(r'^auth/', include('allauth.urls')),
    url(r'^profile/', include('profile.urls')),
    url(r'^file-manager/', include('file_manager.urls')),
    url(r'^admin/', admin.site.urls),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^api/', include(serializersRouter.urls)),
    url(r'', include('home.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

backend/file_manager/urls.py
from django.conf.urls import url

from . import views

app_name = 'file_manager'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

backend/home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ngtest$', views.ng_test, name='ng_test'),
]

backend/profile/urls.py
from django.conf.urls import url

from . import views

app_name = 'profile'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

backend/community/models/post.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.utils.text import slugify

def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='DeletedUser')[0]

class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    body_raw = models.TextField()
    body_html = models.TextField()
    parent = models.ForeignKey('self')
    user = models.ForeignKey(User, on_delete=models.SET(get_sentinel_user))
    is_published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save()

backend/file_manager/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

class Document(models.Model):
    filename = models.CharField(max_length=255, blank=False)
    filetype = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=1024, blank=True)
    slug = models.SlugField(unique=True)
    user = models.ForeignKey(User, on_delete=models.SET(None))
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        #ordering = ['-name ']
        verbose_name = 'Document'
        verbose_name_plural = 'Documents'

    def __str__(self):
        return self.filename

backend/home/models.py
from django.db import models

# Create your models here.

backend/profile/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(default='', blank=True)
    phone = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    country = models.CharField(max_length=255, blank=True)
    organization = models.CharField(max_length=255, blank=True)

    class Meta:
        #ordering = ['-name ']
        verbose_name = 'User Profile'
        verbose_name_plural = 'User Profiles'

    def __str__(self):
        return self.name

    @property
    def name(self):
        return 'profile-'+str(self.id)

backend/djsf/forms.py
from widgets.my_recaptcha import MyReCaptchaField
from allauth.account.forms import SignupForm

class CustomSignupForm(SignupForm):
    captcha = MyReCaptchaField()

backend/community/views.py
from django.shortcuts import render

# Create your views here.

backend/file_manager/views.py
import logging
from django.http import JsonResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User
from django.conf import settings

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

@login_required
def index(request):

    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        print(myfile)
        print(type(myfile))
        print(myfile.content_type)
        print(myfile.size)
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return JsonResponse({'message': 'Success', 'url': '/media/'+myfile.name})


    return render(request, 'file_manager/manager.html', {

    })

backend/home/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'home/index.html', {})

def ng_test(request):
    return render(request, 'home/ng_test.html', {})

backend/profile/views.py
import logging
import io
import json
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.models import User
from profile.models import UserProfile
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser

from django.forms.models import model_to_dict

from djsf.serializers import UserSerializer;
from profile.serializers import  UserProfileSerializator

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

@login_required
def index(request):

    if request.user.is_superuser:
        return redirect('admin:index')

    # send_mail(
    #     'Subject here',
    #     'Here is the message.',
    #     'from@example.com',
    #     ['to@example.com'],
    #     fail_silently=False,
    # )
    #
    # print('Send mail')

    # pprint(request.user)
    # pprint(request.user.is_superuser)
    # pprint(request.user.id)

    logger.debug('XXXXX')

    u = User.objects.get(id=request.user.id)
    u1 = model_to_dict(u, fields=['id', 'email', 'username', 'last_login'])
    uu1 = JSONRenderer().render(u1)
    logger.debug(uu1)
    uu2 = JSONParser().parse(io.BytesIO(uu1))
    u2 = User(**uu2)
    logger.debug(u2)
    logger.debug(u2.last_login)


    # u1 = UserSerializer(u).data
    # # uu1 = JSONRenderer().render(u1)
    # # uu2 = JSONParser().parse(io.BytesIO(uu1))
    #
    # logger.debug(u1)
    # u1['is_staff'] = True
    # logger.debug(u1)
    #
    # u2 = UserSerializer(u, data=u1)
    # logger.debug(u2.is_valid())  # => False
    # logger.debug(u2.validated_data['is_staff'])
    # logger.debug(u2.data)
    # logger.debug(u2.errors)  # => {'username': ['A user with that username already exists.']}



    # resp = {}
    #
    # u = User.objects.get(id=request.user.id)
    # u_ = UserSerializer(u).data
    #
    # resp['user'] = u_
    #
    # logger.debug(u_)
    # logger.debug(type(u_))
    #
    # up = UserProfile.objects.get(user_id=2)
    # up_ = UserProfileSerializator(up).data
    #
    # resp['profile'] = up_
    #
    # logger.debug(up_)
    # logger.debug(type(up_))
    #
    # respJSON = JSONRenderer().render(resp)
    #
    # logger.debug(respJSON)
    # logger.debug(type(respJSON))
    #
    # data2 = JSONParser().parse(io.BytesIO(respJSON))
    #
    # u2_ = UserSerializer(data=data2['user'])
    #
    # # up2_ = UserProfileSerializator(data=data2['profile'])
    #
    #
    # logger.debug(u2_)
    # logger.debug(u2_.is_valid())
    # logger.debug(u2_.errors)
    # logger.debug(u2_.data)
    # logger.debug(u2_.instance)
    # #logger.debug(u2_.instance.username)
    # logger.debug(type(u2_))

    # logger.debug(up2_)
    # logger.debug(up2_.is_valid())
    # logger.debug(up2_.errors)
    # logger.debug(up2_.data)
    # logger.debug(type(up2_))

    #logger.debug(JSONRenderer().render(UserProfileSerializator(up).data))

    messages.add_message(request, messages.SUCCESS, 'Welcome to profile page!!!')
    # messages.add_message(request, messages.INFO, 'Hello world.')
    # messages.add_message(request, messages.ERROR, 'Hello world.')
    # messages.add_message(request, messages.WARNING, 'Hello world.')




    return render(request, 'profile/index.html', {})

backend/file_manager/templates/file_manager/manager.html
{% extends "base.html" %}
{% load static %}
{% load account %}
{% block head %}

{% endblock %}
{% block content %}

    <script>
    $(document).ajaxSend(function (event, jqxhr, settings) {
        jqxhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
    });
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/9.19.2/js/vendor/jquery.ui.widget.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/9.19.2/js/jquery.iframe-transport.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/9.19.2/js/jquery.fileupload.js"></script>

    <app-root></app-root>

    <script type="text/javascript" src="{% static '/apps/file-manager/inline.bundle.js'%}"></script>
    <script type="text/javascript" src="{% static '/apps/file-manager/polyfills.bundle.js'%}"></script>
    <script type="text/javascript" src="{% static '/apps/file-manager/vendor.bundle.js'%}"></script>
    <script type="text/javascript" src="{% static '/apps/file-manager/main.bundle.js'%}"></script>

{% endblock %}

backend/file_manager/templates/file_manager/manager_s3.html
<html>
    <head>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/9.19.2/js/vendor/jquery.ui.widget.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/9.19.2/js/jquery.fileupload.min.js"></script>

    </head>
    <body>

        <form action="https://{{s3.bucket}}.s3.amazonaws.com/" method="post" enctype="multipart/form-data">
            <!-- /user/user1/${filename} -->
            <input type="hidden" name="key" value="{{s3.prefix}}{{s3.amz_date}}_${filename}" />
            <!-- private | public-read | public-read-write | authenticated-read | bucket-owner-read | bucket-owner-full-control -->
            <input type="hidden" name="acl" value="public-read" />
            <!-- The signing algorithm used to authenticate the request. For AWS Signature Version 4, the value is AWS4-HMAC-SHA256 -->
            <input type="hidden" name="X-Amz-Algorithm" value="{{s3.amz_algorithm}}" />
            <!-- <your-access-key-id>/<date>/<aws-region>/<aws-service>/aws4_request -->
            <input type="hidden" name="X-Amz-Credential" value="{{s3.amz_credential}}" />
            <!-- It is the date value in ISO8601 format. For example, 20130728T000000Z. -->
            <input type="hidden" name="X-Amz-Date" value="{{s3.amz_date}}" />
            <input type="hidden" name="success_action_status" value="200" />
            <input type="hidden"  name="Content-Type" value="image/jpeg" />
            <!-- The Base64 encoded security policy that describes what is permitted in the request -->
            <input type="hidden" name="Policy" value="{{s3.policy}}" />
            <!-- (AWS Signature Version 4) The HMAC-SHA256 hash of the security policy. -->
            <input type="hidden" name="X-Amz-Signature" value="{{s3.signature}}" />
            <span class="slds-button slds-button_success fileinput-button">
                <i class="glyphicon glyphicon-plus"></i>
                <!-- The file input field used as target for the file upload widget -->
                <input id="fileupload" type="file" name="file" multiple />
            </span>
            <button class="slds-button slds-button_brand" >UPLOAD!</button>
        </form>

        <script>

            window.ssend = function(){
                $('#fileupload').fileupload('send', {files: window.ffiles});
            }

            function initUploadImageToS3() {
                var url = 'https://{{s3.bucket}}.s3.amazonaws.com/';
                jQuery('#fileupload').fileupload({
                    forceIframeTransport: false,
                    singleFileUploads: true,
                    url: url,
                    add: function(e, data) {

                        console.log('ADD')
                        console.log(data);

                        //window.ffiles = data.originalFiles;

                        data.submit();

                        /*
                        var uploadErrors = [];
                        var acceptFileTypes = /^image\/(gif|jpe?g|png)$/i;
                        for (var i=0; i<data.originalFiles.length; i++) {
                            var file = data.originalFiles[i];
                            if(file['type'].length && !acceptFileTypes.test(file['type'])) {
                                uploadErrors.push('{!$Label.UI_Text_Not_an_accepted_file_type}');
                            }
                            if(file['size'] > 3000000) {
                                uploadErrors.push('{!$Label.UI_Text_Filesize_is_too_big}');
                            }
                        }
                        if(uploadErrors.length > 0) {
                            ractiveImage.set('uploadMessage', uploadErrors.join("\n"));
                        } else {
                            var sendReq = data.submit();
                            ractiveImage.set('uploadMessage', null);
                            ractiveImage.set('uploadInProgress', true);
                            ractiveImage.set('uploadedImages', []);
                        }
                        */
                    },
                    done: function (e, data) {
                        console.log(data)
                        /*
                        ractiveImage.set('uploadInProgress', false);
                        if (data.jqXHR.status == 200) {
                            for (var i=0; i<data.files.length; i++) {
                                var fileName = data.files[i].name.replace(/[#%+']/g, '-');//use the same approach as in send function to use same name.
                                var fileUrl = "https://{!s3.bucket}.s3.amazonaws.com/{!s3.keyEncoded}{!s3.unixDatetime}_"+encodeURIComponent(fileName);
                                var image = new Image();
                                image.src = fileUrl;
                                image.onload = function() {
                                    ractiveImage.push('uploadedImages', {
                                        filename: fileName,
                                        url: fileUrl,
                                        // {!$ObjectType.Image__c.fields.Tags__c.name}: initTags,
                                    });
                                };
                                image.onerror = function() {
                                    ractiveImage.set('uploadedImages', []);
                                    ractiveImage.set('uploadMessage', '<span style="color: #FF0000;">{!$Label.UI_Text_Image_Not_uploaded_to_S3}</span>');
                                };
                            }
                        } else {
                            ractiveImage.set('uploadMessage', '<span style="color: #FF0000;">{!$Label.UI_Label_Error}</span>');
                        }
                        */
                    },
                    send: function (e, data) {
                        console.log(data)
                        /*
                        var file = data.files[0];
                        var newFileName = file.name.replace(/[#%+']/g, '-');
                        //file.name - is read only. in this case we replace this file in formData. Warning!!! data.files and data.originalFiles still contains old name.
                        data.data.set('file', file, newFileName);
                        */
                    },
                }).prop('disabled', !jQuery.support.fileInput).parent().addClass(jQuery.support.fileInput ? undefined : 'disabled');
            }

            initUploadImageToS3();
        </script>

    </body>
</html>

backend/home/templates/home/index.html
{% extends "base.html" %}
{% load static %}
{% load account %}
{% block head %}

{% endblock %}
{% block content %}
	<h1>HOME</h1>

	{% user_display user %}

{#	<div>#}
{#		{% verbatim %}#}
{#		<div id="app">#}
{#			{{ message }}#}
{#		</div>#}
{#		{% endverbatim %}#}
{#	</div>#}

{% endblock %}

backend/home/templates/home/ng_test.html
{% extends "base.html" %}
{% load static %}
{% load account %}
{% block head %}

{% endblock %}
{% block content %}
    <app-root></app-root>

{#    <script type="text/javascript" src="{% static '/apps/inline.bundle.js'%}"></script>#}
{#    <script type="text/javascript" src="{% static '/apps/polyfills.bundle.js'%}"></script>#}
{#    <script type="text/javascript" src="{% static '/apps/vendor.bundle.js'%}"></script>#}
{#    <script type="text/javascript" src="{% static '/apps/file-manager.bundle.js'%}"></script>#}

    <script type="text/javascript" src="{% static '/apps/profile/inline.bundle.js'%}"></script>
    <script type="text/javascript" src="{% static '/apps/profile/polyfills.bundle.js'%}"></script>
    <script type="text/javascript" src="{% static '/apps/profile/vendor.bundle.js'%}"></script>
    <script type="text/javascript" src="{% static '/apps/profile/main.bundle.js'%}"></script>

{% endblock %}

backend/home/templates/my_recaptcha/widget.html
<div>
    <style>
        .g-recaptcha > div {
            margin: auto;
        }
    </style>
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <div class="g-recaptcha" data-sitekey="{{ public_key }}"></div>
</div>

backend/profile/templates/profile/index.html
{% extends "base.html" %}
{% load static %}
{% block head %}

{% endblock %}
{% block content %}
	<h1>Profile here ...</h1>


{#    <script>#}
{#        setInterval(function() {#}
{#            console.log('D');#}
{#            MessagesService.add(MessagesService.ERROR, 'Super error');#}
{#        }, 1000)#}
{#    </script>#}

{% endblock %}

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>{% block title %}DJSF{% endblock %}</title>
	<script
		src="https://code.jquery.com/jquery-3.2.1.min.js"
		integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
		crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
	<script src="https://use.fontawesome.com/14ee000d5e.js"></script>
	<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,400i,500,700&amp;subset=cyrillic" rel="stylesheet">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.3.2/spin.min.js"></script>

    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.171.0.min.js"></script>

	{% load static %}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/design-system/2.4.5/styles/salesforce-lightning-design-system.css">
	<link rel="stylesheet" href="{% static 'global.css' %}">
	{% block head %}{% endblock %}
</head>
<body>
    <div id="c-container">
        <div class="c-header">
            <div class="slds-grid">
                <div class="slds-col">
                    <a href="{% url 'home:index' %}" class="c-logo-link">
                        <img src="{% static 'icon3.png' %}" alt="E2 CMS Logo" class="c-logo" />
                        <span class="c-site-title">DJSF</span>
                    </a>
                </div>
                <div class="slds-col">

                </div>
            </div>
        </div>
        <div class="c-sub-header">
            <div class="slds-grid">
                <div class="slds-col"></div>
                <div class="slds-col c-right">
                    {% if user.is_authenticated %}
                        Welcome <a href="{% url 'profile:index' %}">{{ user.username }}</a>, <a href="{% url 'account_logout' %}">Sign out</a>
                    {% else %}
                        <a href="{% url 'account_login' %}">Sign In</a>
                        &nbsp;
                        <a href="{% url 'account_signup' %}">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="c-messages-box"></div>

        <div class="c-content">
            {% block content %}{% endblock %}
        </div>
        <div class="c-footer">
            {% block footer %}
            &copy; Copyright 2017 by Dmitry Shnyrev.
            {% endblock %}
        </div>
    </div>

    {% include "messages-service.html" %}

</body>
</html>

backend/templates/messages-service.html
{% load static %}
<script id="c-messages-box-template" type="text/template">
    <% _.forEach(messages, function(message, index) { %>
    <div class="slds-notify slds-notify_alert slds-theme_alert-texture slds-theme_<%- message.type %>" role="alert">
        <h2><%- message.text %></h2>
        <button class="slds-button slds-button_icon slds-notify__close slds-button_icon-inverse c-remove-message-button" data-index="<%- index %>" title="Close">
            <svg class="slds-button__icon" aria-hidden="true">
                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="{% static 'libs/slds245/assets/icons/utility-sprite/svg/symbols.svg'%}#close" />
            </svg>
            <span class="slds-assistive-text">Close</span>
        </button>
    </div>
    <% }); %>
</script>

<script>

    var MessagesService = {
        INFO: 'info',
        ERROR: 'error',
        WARNING: 'warning',
        SUCCESS: 'success',
        messagesBox: jQuery('.c-messages-box'),
        messagesBoxTemplate: _.template(jQuery('#c-messages-box-template').text()),
        messages: [
            {% if messages %}
                {% for message in messages %}
                    {type: '{{ message.tags }}', text: '{{ message }}'},
                {% endfor %}
            {% endif %}
        ],
        render: function() {
            console.log('MESSAGES:');
            console.log(this.messages);
            var messagesHtml = this.messagesBoxTemplate({messages: this.messages});
            this.messagesBox.html(messagesHtml);
            this.messagesBox.find('.c-remove-message-button').each(function() {
                jQuery(this).off('click').on('click', function() {
                    var index = jQuery(this).data('index');
                    MessagesService.messages.splice(index, 1);
                    MessagesService.render();
                })
            })
        },
        add: function(type, text) {
            this.messages.push({type: type, text: text});
            this.render();
        },
        clear: function() {
            this.messages = [];
        }
    };

    MessagesService.render();

</script>